### ISSUE TITLE
好喜欢这个主题！请问能不能加个tag功能

### ISSUE THREAD

**Issue by 49092095** [lh1me/hexo-theme-aomori#1]
你好，
刚刚开始用hexo，翻到了你的主题，好喜欢侧边栏和目录结合啊，好酷！
请问你有没有想法增加tag功能，或者方便指路怎么自己写嘛

**Comment by lh1me** [comment]
你好，我们支持官网所有的 Front-matter，具体请查阅文档 https://hexo.io/zh-cn/docs/front-matter

**Comment by lh1me** [comment]
> 你好，
> 刚刚开始用hexo，翻到了你的主题，好喜欢侧边栏和目录结合啊，好酷！
> 请问你有没有想法增加tag功能，或者方便指路怎么自己写嘛

你好，我们支持官网所有的 Front-matter，具体请查阅文档 https://hexo.io/zh-cn/docs/front-matter

**Comment by 49092095** [comment]
感谢！试了一下成功了！
以及我正在尝试加入gitalk，根据这个教程修改了路径，[https://segmentfault.com/a/1190000014085547](https://segmentfault.com/a/1190000014085547)
但修改了以后文章下面并没有任何东西加载出来……求问能不能有空加个gitalk！

**Comment by 49092095** [comment]
我添加成功了！我去研究怎么加Valine

**Comment by 49092095** [comment]
好了，我学会了！请问最后一个问题，[https://github.com/hustcc/clz#usage](https://github.com/hustcc/clz#usage)里
这里的import是放在哪个格式的文件里啊？article.ejs吗？

**Comment by lh1me** [comment]
> 好了，我学会了！请问最后一个问题，https://github.com/hustcc/clz#usage里
> 这里的import是放在哪个格式的文件里啊？article.ejs吗？

不太清楚，没有用过这个。后续会抽空添加 Gitalk。
