### ISSUE TITLE
footer没有完全置底

### ISSUE THREAD

**Issue by cornorghost** [lh1me/hexo-theme-aomori#11]
当页面内容较少时footer会不置底，虽然我修改了一下style.scss文件的样式，但是没起作用，而且好像修改scss不会起作用，我是新手，不知道弄得对不对
![image](https://user-images.githubusercontent.com/33841855/87071055-43432b80-c24c-11ea-95d6-33daaa9504f7.png)

**Comment by lh1me** [comment]
> 当页面内容较少时footer会不置底，虽然我修改了一下style.scss文件的样式，但是没起作用，而且好像修改scss不会起作用，我是新手，不知道弄得对不对
> ![image](https://user-images.githubusercontent.com/33841855/87071055-43432b80-c24c-11ea-95d6-33daaa9504f7.png)

前端需要构建

**Comment by cornorghost** [comment]
> > 当页面内容较少时footer会不置底，虽然我修改了一下style.scss文件的样式，但是没起作用，而且好像修改scss不会起作用，我是新手，不知道弄得对不对
> > ![image](https://user-images.githubusercontent.com/33841855/87071055-43432b80-c24c-11ea-95d6-33daaa9504f7.png)
> 
> 前端需要构建

我重新构建了一下，我在footer的上一个物件的样式加一个
```
max-width: inherit;
```
这样看起来footer置底了，不过整个页面拉长了不少

**Comment by cornorghost** [comment]
> > 当页面内容较少时footer会不置底，虽然我修改了一下style.scss文件的样式，但是没起作用，而且好像修改scss不会起作用，我是新手，不知道弄得对不对
> > ![image](https://user-images.githubusercontent.com/33841855/87071055-43432b80-c24c-11ea-95d6-33daaa9504f7.png)
> 
> 前端需要构建

我重新构建了，只能在main的样式里把min-height调高，这样看起来会好一点
```
min-height: 800px;
```

**Comment by lh1me** [comment]
期待你能用内容撑起你的BLOG~
