### ISSUE TITLE
显示没有_partial/page/page

### ISSUE THREAD

**Issue by Hu5k7** [lh1me/hexo-theme-aomori#12]
![1](https://user-images.githubusercontent.com/48304095/87118483-1cb5dc80-c2ae-11ea-832e-7f5c6ee05a34.png)

**Comment by Hu5k7** [comment]
文章也不闭合
![微信截图_20200710130717](https://user-images.githubusercontent.com/48304095/87118572-525ac580-c2ae-11ea-92fa-fe9e3fce0bb0.png)

**Comment by lh1me** [comment]
layout 填错了
