### ISSUE TITLE
gitalk的id过长问题

### ISSUE THREAD

**Issue by cornorghost** [lh1me/hexo-theme-aomori#13]
最近出现了评论区gitalk validation failed的问题，查看了gitalk的issuse发现是id过长的问题，需要使用md5来简化id，大佬知道要怎么在gitalk.js里使用md5吗

**Comment by lh1me** [comment]
> 最近出现了评论区gitalk validation failed的问题，查看了gitalk的issuse发现是id过长的问题，需要使用md5来简化id，大佬知道要怎么在gitalk.js里使用md5吗

我看了一下，应该是文章URL过长问题，我加个md5配置吧

**Comment by lh1me** [comment]
已经更新了

**Comment by cornorghost** [comment]
感谢大佬，大佬真是神速啊



---原始邮件---
发件人: "LIN HONG"<notifications@github.com&gt;
发送时间: 2020年7月22日(周三) 上午10:48
收件人: "lh1me/hexo-theme-aomori"<hexo-theme-aomori@noreply.github.com&gt;;
抄送: "ghost cornor"<1648313898@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [lh1me/hexo-theme-aomori] gitalk的id过长问题 (#13)




 
已经更新了

**Comment by cornorghost** [comment]
已经解决了，可以正确初始化issue
