### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by zoyua** [lh1me/hexo-theme-aomori#144]
很喜欢这款主题，对作者的开源表示感谢。另外想提个小小的建议，能否更多的支持可配置化，个人认为可以配置的项有些少，比如字体大小，背景图，分享方式等。虽然可以通过修改源代码来实现，但是既然已经提供了直接npm安装主题的方式，再去修改源代码总归是不方便的。而且当主题有更新的时候去merge也可能会有冲突，所以还是配置化更方便一些。希望作者考虑下，谢谢。

**Comment by zoyua** [comment]
还有一点就是搜索使用Algolia其实不是很方便，毕竟要请求后端服务，我之前看别的主题可以实现本地搜索这种，而且速度更快，不知道作者是否可以支持。

**Comment by lh1me** [comment]
1. Algolia 能实现自动内容分析和关键词检索，本地搜索不能，基本搜不出想要的东西，不推荐使用本地搜索
2. 主题会在后续迭代中考虑部份内容的可配置
