### ISSUE TITLE
关于tweet这个layout类型的小疑问

### ISSUE THREAD

**Issue by LWanTao** [lh1me/hexo-theme-aomori#154]
不好意思本人不擅长前端，想请教一下：

我将一篇文章的Front-matter设置为

```
---
layout: tweet
icon: chatbox
tags: 碎碎念
---
```

然后在右侧RECENT POSTS会出现(no title),可是我看您的博客不会将tweet类型的文章计入RECENT POSTS中，我似乎没有在GitBook中找到，请问这样该如何设置？

另外一提，不如把GitBook开源，大家一起共建？我觉得您的主题设计的很好，一定会越来越受欢迎的 : )

**Comment by lh1me** [comment]
`title` 字段是一定要有的，我们没有改变文章在 Hexo 下的定义，只是调整了样式，文章依旧会在 Recent Posts 中显示的。

**Comment by LWanTao** [comment]
了解，是我疏忽了，您的Recent Posts中确实也是有显示tweet类型文章，感谢您的回复！
