### ISSUE TITLE
想請問作者header-type-title的href是吃設定檔的哪個參數？

### ISSUE THREAD

**Issue by YawenChan** [lh1me/hexo-theme-aomori#156]
Hi 開發者您好：

如題，目前使用您開發的主題，但在href的變數會產生錯誤，會把頁面導向此 => https://yawenchan.github.io/
目前有查看過_config.yml檔案，也沒發現有這樣的設定，再麻煩解惑了，十分感謝！

Thanks,
Mika Chan

**Comment by LWanTao** [comment]
我看了一下你的仓库，你是在本地编译完静态站点再部署到 GitHub 仓库上的吧？

我好久没有见过这种情况了，或许你可以尝试：

根据 Hexo 官方文档，在根目录里的全局配置文件 config.yml 中配置

```
# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://yawenchan.github.io/blog.github.io/
root: / # 或者 root: /blog.github.io/
```
> 参考链接：https://hexo.io/zh-cn/docs/configuration#%E7%BD%91%E5%9D%80

**Comment by YawenChan** [comment]
非常感謝!
