### ISSUE TITLE
Ability to change the accent color

### ISSUE THREAD

**Issue by ghost** [lh1me/hexo-theme-aomori#18]
Not everyone likes the default dark green accent color, can it be modified to be configurable?

**Comment by lh1me** [comment]
That is a feature, Welcome PR if you can.

**Comment by Fei1Yang** [comment]
After checking the build process, I found that there seemed to be no easy way to modify the accent color without rebuild SCSSes. so I think the best way is to provide an option to load custom css file to override the existing colors. is this way acceptable?

**Comment by lh1me** [comment]
The most ideal way is to get rid of the CSS file, completely extract the color, and set the color through the configuration file, but this will greatly change the overall code. According to your needs, I have extracted the color variables in style.scss. You can change the variables and rebuild them to achieve your needs.
