### ISSUE TITLE
algolia使用配置问题

### ISSUE THREAD

**Issue by cornorghost** [lh1me/hexo-theme-aomori#20]
首先博主真的神速，前不久说了这个功能，现在就完成了
但是我配置key的时候出错，这里选择哪个key都不好使，博主使用的是Search-Only API Key还是Usage API Key

**Comment by lh1me** [comment]
有两个地方需要设置 Key 的，站点配置里配置的是 Search-Only API Key，命令行更新数据需要配置 Admin API Key

**Comment by cornorghost** [comment]
已经设置成功了，功能很棒，只需要每次发文章加一个hexo algolia就可以对吧

**Comment by lh1me** [comment]
> 已经设置成功了，功能很棒，只需要每次发文章加一个hexo algolia就可以对吧

是的
