### ISSUE TITLE
new footer太酷了，不过在pc端看起来有点高了

### ISSUE THREAD

**Issue by cornorghost** [lh1me/hexo-theme-aomori#22]

**Comment by cornorghost** [comment]
而且这次更新除了footer还有别的更新吗，我合并了你的分支后header出现了问题

**Comment by lh1me** [comment]
> 而且这次更新除了footer还有别的更新吗，我合并了你的分支后header出现了问题

截图看看是什么问题

**Comment by cornorghost** [comment]
> > 而且这次更新除了footer还有别的更新吗，我合并了你的分支后header出现了问题
> 
> 截图看看是什么问题

![image](https://user-images.githubusercontent.com/33841855/92318470-1a1dfc00-f03f-11ea-965a-22a6db1537a0.png)
