### ISSUE TITLE
文章封面图片问题

### ISSUE THREAD

**Issue by Phukety** [lh1me/hexo-theme-aomori#27]
您好！我有个疑问就是参照你的配置，但是始终不能像demo那样展示文章的格式，包含图片和标题文字。

可以发一份demo的参考md文件和_config文件吗,非常感谢！

**Comment by lh1me** [comment]
你好，你可以直接提供你的配置，我帮你看看什么问题

**Comment by Phukety** [comment]
> 你好，你可以直接提供你的配置，我帮你看看什么问题

谢谢，我已经弄好了。但还有几个疑问：
1.文章封面的高度是和封面图片相关的吗
2.封面的图片好像不能以文章对应的资源目录来访问图片(比如直接访问avatar.jpg),只能通过source目录下images/avatar.jpg来访问
3.aomori_social的icon不生效(是空白)，但链接有效，是图片路径不对吗

这是我的博客的[_config配置地址](https://github.com/Phukety/Phukety-blog/blob/master/_config.yml)

感谢回复！

**Comment by lh1me** [comment]
封面图只限制宽度，不限制高度，保证图片完整显示。封面图支持对应文章资源目录，参照demo的图片路径。你的配置文件里aomori_social的icon和type都没填，去boxicons拿需要的icon name和type，type没有就不要。

**Comment by Phukety** [comment]
> 封面图只限制宽度，不限制高度，保证图片完整显示。封面图支持对应文章资源目录，参照demo的图片路径。你的配置文件里aomori_social的icon和type都没填，去boxicons拿需要的icon name和type，type没有就不要。

去boxicons下载吗，我不是很懂，还是直接url访问呢。
