### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by miknai** [lh1me/hexo-theme-aomori#28]
I have followed the manual up to the Using section as below:
1. Enable Theme
2. Turn off Hexo default Highlight

Then, I tried to run "hexo server", but I get this error:

Unhandled rejection TypeError: /Users/geonsookim/Desktop/miknai.github.io/themes/hexo-theme-aomori/layout/layout.ejs:20
    18|             <aside class="sidebar">
    19|             <% } %>
 **20|                 <%- partial('_partial/sidebar') %>**
    21|             </aside>
    22|         </div>
    23|     </div>

/Users/geonsookim/Desktop/miknai.github.io/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
    5| 
    6| <div class="widget" id="widget">
 **7|     <% config.aomori_widgets.forEach(function(widget){ %>**
    8|       <%- partial('_widget/' + widget) %>
    9|     <% }) %>
    10| </div>

Cannot read property 'forEach' of undefined

**Comment by lh1me** [comment]
**aomori_widgets** is not configured.

**Comment by miknai** [comment]
Oops. sorry that I missed it. Works great now. Thank you!
