### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by Sunnie-Y** [lh1me/hexo-theme-aomori#32]
怎么能在主页把内容全部或部分折叠起来，而不是展示整篇文章的内容，有的文章太长了，影响上下翻阅

**Comment by lh1me** [comment]
你需要的是否是这个页面 https://linhong.me/archives/

**Comment by Sunnie-Y** [comment]
![image](https://user-images.githubusercontent.com/66898535/99348330-51791680-28d4-11eb-9420-0a59058ad037.png)
像这样，在home page 通过点击文章的标题打开文章，而不是把文章完全展示，感觉这样比较好看。

**Comment by Sunnie-Y** [comment]
![image](https://user-images.githubusercontent.com/66898535/99348548-d19f7c00-28d4-11eb-8c64-f6b6fd46150c.png)
差不多是这个样子，在home page 不是如数展示文章的内容

**Comment by lh1me** [comment]
建议尽量不要在列表页展示过多的文章内容。
如果实在有需要，建议调整 **per_page** 分页。
