### ISSUE TITLE
关于视频播放

### ISSUE THREAD

**Issue by cornorghost** [lh1me/hexo-theme-aomori#35]
刚好前段时间想在博客放个视频，捣鼓半天使用dplayer播放本地视频，结果播放控件全是乱的，无奈只能用iframe，结果刚好你这支持嵌入本地视频，真是太棒了，而且效果还很好，不过有个问题是播放视频时卡顿，这是我自己服务器的问题吗，而且使用video的时候，源如果是链接的话，会导致播放不了吗

**Comment by lh1me** [comment]
视频卡顿基本是因为网络问题。
源的链接不影响播放，只要能直接用 <video> 标签播放就可以。
无法播放的原因有很多种，要具体看问题。
