### ISSUE TITLE
我尝试在_config.yml写入主题配置，但是好像不生效

### ISSUE THREAD

**Issue by VIlboys** [lh1me/hexo-theme-aomori#37]
如题

**Comment by lh1me** [comment]
请发一下你的配置

**Comment by VIlboys** [comment]
我是在主题的_config.yml文件里面写入






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LIN HONG"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 上午9:29
收件人: "lh1me/hexo-theme-aomori"<hexo-theme-aomori@noreply.github.com&gt;; 
抄送: "笑"<1399833047@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lh1me/hexo-theme-aomori] 我尝试在_config.yml写入主题配置，但是好像不生效 (#37)





 
请发一下你的配置
