### ISSUE TITLE
添加 about 页面报错

### ISSUE THREAD

**Issue by laugh12321** [lh1me/hexo-theme-aomori#40]
在终端输入`hexo new page about`，并在`_config.yml`中添加了头部菜单`About: /about`，部署后出现报错，如下：

```
ERROR Error: E:\50368\Documents\Hexo\blog\node_modules\hexo-theme-aomori\layout\page.ejs:3
    1|
    2| <div class="<%= page.layout %>">
 >> 3|   <%- partial(`_partial/page/${page.layout}`, {post: page, index: false}) %>
    4| </div>

Partial _partial/page/about does not exist. (in page.ejs)
    at Object.partial (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
    at eval (E:\50368\Documents\Hexo\blog\node_modules\hexo-theme-aomori\layout\page.ejs:15:17)
    at page (E:\50368\Documents\Hexo\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\50368\Documents\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\50368\Documents\Hexo\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\50368\\Documents\\Hexo\\blog\\node_modules\\hexo-theme-aomori\\layout\\page.ejs'
}
```

<b>PS：</b>相同步骤创建友情链接页面正常

**Comment by lh1me** [comment]
> 在终端输入`hexo new page about`，并在`_config.yml`中添加了头部菜单`About: /about`，部署后出现报错，如下：
> 
> ```
> ERROR Error: E:\50368\Documents\Hexo\blog\node_modules\hexo-theme-aomori\layout\page.ejs:3
>     1|
>     2| <div class="<%= page.layout %>">
>  >> 3|   <%- partial(`_partial/page/${page.layout}`, {post: page, index: false}) %>
>     4| </div>
> 
> Partial _partial/page/about does not exist. (in page.ejs)
>     at Object.partial (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\plugins\helper\partial.js:16:11)
>     at eval (E:\50368\Documents\Hexo\blog\node_modules\hexo-theme-aomori\layout\page.ejs:15:17)
>     at page (E:\50368\Documents\Hexo\blog\node_modules\ejs\lib\ejs.js:682:17)
>     at _View._compiled (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\theme\view.js:136:50)
>     at _View.render (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\theme\view.js:39:17)
>     at E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\hexo\index.js:64:21
>     at tryCatcher (E:\50368\Documents\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at E:\50368\Documents\Hexo\blog\node_modules\bluebird\js\release\method.js:15:34
>     at RouteStream._read (E:\50368\Documents\Hexo\blog\node_modules\hexo\lib\hexo\router.js:47:5)
>     at RouteStream.Readable.read (internal/streams/readable.js:481:10)
>     at resume_ (internal/streams/readable.js:968:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   path: 'E:\\50368\\Documents\\Hexo\\blog\\node_modules\\hexo-theme-aomori\\layout\\page.ejs'
> }
> ```
> 
> PS：相同步骤创建友情链接页面正常

主题并没有 **about** 这个模版。请参考官方文档 [https://hexo.io/zh-cn/docs/writing](https://hexo.io/zh-cn/docs/writing)

**Comment by laugh12321** [comment]
问题已解决！

在`hexo-theme-layout/layout/_partial/page`下添加`about.ejs`文件，并写入一下代码：

```ejs
<% if (post.content){ %>
<article
  id="<%= post.layout %>-<%= post._id %>"
  class="article article-type-<%= post.layout %>"
>
    <div class="article-inner">
        <div class="article-entry post-inner-html">
            <%- post.content %>
        </div>
    </div>
</article>
<% } %>
```
若想添加评论功能，还可添加以下代码：

```ejs
<% if (post.comment && config.aomori_disqus_shortname){ %>
<section class="comments">
  <div id="disqus_thread"></div>
  <script>
      (function () { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://<%- config.aomori_disqus_shortname %>.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
      })();
  </script>
</section>
<% } %>

<% if (post.comment && config.aomori_gitalk){ %>
<section class="comments">
  <div id="gitalk-container"></div>
</section>
<% } %>
```
（即将`friends.ejs`相应的代码段复制过来即可）

如果觉得自定义页面的`title`不美观，可在`hexo-theme-layout/layout/_partial/header.ejs`中注释掉以下代码：

```ejs
<% if (is_page()){ %>
  <span class="header-type-page-title"><%= page.title %></span>
<% } %>
```

**Comment by lh1me** [comment]
新版本增加了新的默认页面模版解决这个问题了
