### ISSUE TITLE
无法生成和显示数学公式

### ISSUE THREAD

**Issue by spiderman-spiderman** [lh1me/hexo-theme-aomori#44]
亲爱的作者你好，我在配置数学公式时操作如下，但是不能显示出数学公式：
1、npm install hexo-math --save
2、站点配置文件
     math:
         engine: 'mathjax' 
         mathjax:
3、主题配置文件
     math:
         enable: true
         engine: mathjax
     mathjax:
        enable: true
        cdn: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
这3步操作后，在文章中加入数学公式，不能够显示，请问这种问题应该如何去解决，如有答案还请指点，谢谢

**Comment by lh1me** [comment]
根据 [hexo-math](https://github.com/hexojs/hexo-math) 文档中所示的使用范例，并没有你所述的配置

我在本地运行没有出现问题，如果你的运行有报错可以发一下报错信息

**Comment by spiderman-spiderman** [comment]
并没有报错，只是没有显示出公式
文章中的格式如下：
<font color = "black">几何关系可以写成：$$\cos2\theta = cos^2\theta - \sin^2 \theta \\ =  2\cos^2\theta -1$$</font>

显示效果是
几何关系可以写成：

**Comment by lh1me** [comment]
确认一下你的依赖是否为最新的，参照官方文档，你的公式的写法应该为

```
{% mathjax %}
\cos2\theta = cos^2\theta - \sin^2 \theta \ = 2\cos^2\theta -1
{% endmathjax %}
```

**Comment by spiderman-spiderman** [comment]
多谢，我的问题已解决，公式的写法有问题
