### ISSUE TITLE
关于首页文章封面问题

### ISSUE THREAD

**Issue by holk-h** [lh1me/hexo-theme-aomori#45]
作者您好，我安装 hexo-renderer-marked 之后，首页封面就无法正常显示了，同时查看封面图片标签的src为/[名字].jpg
应如何解决？
<img width="889" alt="Screenshot 2021-04-16 at 11 16 25" src="https://user-images.githubusercontent.com/29571233/114966477-37545c00-9ea5-11eb-9cf9-5e9f4edd3669.png">

**Comment by lh1me** [comment]
你需要查看 **hexo-renderer-marked** 静态资源路径相关配置

**Comment by lh1me** [comment]
首先，根据你的描述，你是在成功使用封面图后，安装了 hexo-renderer-marked，然后封面图失效。
