### ISSUE TITLE
年份分类会错乱，出现多个一样的

### ISSUE THREAD

**Issue by Oct1a** [lh1me/hexo-theme-aomori#48]
博客地址：http://blogs.dllca.cn/右侧的ARCHIVE

**Comment by lh1me** [comment]
配置文件 **_config.yml** 中设置 `archive_type: 'yearly'`

**Comment by Oct1a** [comment]
> 配置文件 **_config.yml** 中设置 `archive_type: 'yearly'`

嗯，可以了，谢谢
