### ISSUE TITLE
置顶和转发的icon 显示不出来，

### ISSUE THREAD

**Issue by FussenYu** [lh1me/hexo-theme-aomori#53]
看了下网络请求显示301 moved permanently 

就这两个icon

<box-icon type='solid' name='to-top' color='#ffffff' size='xs'></box-icon>

<box-icon name='repost' color='#ffffff' size='xs'></box-icon>

没有截图

本地运行可以正常显示，放到服务器上就无法显示了

**Comment by lh1me** [comment]
提供一下 301 请求的 url

**Comment by FussenYu** [comment]
https://unpkg.com/boxicons@2.0.9/svg/solid/bxs-to-top.svg

就是这个链接显示不出来

**Comment by FussenYu** [comment]
> 提供一下 301 请求的 url

https://unpkg.com/boxicons@2.0.9/svg/solid/bxs-to-top.svg

就是这个链接显示不出来

**Comment by FussenYu** [comment]
截图和链接来了 [这是临时截图链接](https://tva1.sinaimg.cn/large/008i3skNgy1gtmgo81cblj61na0u0wip02.jpg)

**Comment by lh1me** [comment]
浏览器显示提示已经说的很明确了，你用 localhost 访问不在跨域允许范围内。
