### ISSUE TITLE
目录高度显示不够

### ISSUE THREAD

**Issue by YINNA63** [lh1me/hexo-theme-aomori#55]
![image](https://user-images.githubusercontent.com/33350067/131223797-d714cb7c-b355-43f2-b335-6f215a0f8b47.png)

**Comment by lh1me** [comment]
请提供一下更完整的图例

**Comment by YINNA63** [comment]
![image](https://user-images.githubusercontent.com/33350067/132126615-7bbc1f63-ef8d-4be1-a2b0-1bcfba0ab802.png)
