### ISSUE TITLE
希望代码块宽度固定到页面同宽，并增加可配置性

### ISSUE THREAD

**Issue by YINNA63** [lh1me/hexo-theme-aomori#56]
现在代码块的宽度是由最长的一行代码长度决定的，并且居中显示，看着不太舒服呀，能不能换成和文字一样固定宽度到和可以显示文字内容一样那么宽，这样比较统一。并且如果代码过长的话能否自动换行呢，现在会超出可显示范围，然后一直超出页面
![image](https://user-images.githubusercontent.com/33350067/131223819-293f97da-b357-4c87-971d-206c7e86c87a.png)

另外看到作者在一开始就把代码的 style enable给关了，这个是有什么冲突嘛，希望可以配置语言之类的哦

谢谢，辛苦了！

**Comment by lh1me** [comment]
我们覆盖掉了 Hexo 提供的默认代码高亮，请先尝试 [关闭默认配置](https://github.com/lh1me/hexo-theme-aomori#using)

**Comment by YINNA63** [comment]
嗯嗯，所以想说能否在已经覆盖以统一风格的前提下，也能和默认配置一样支持那些可配置项呢？尤其是代码宽度这一点，感觉默认就应该和页面同宽而不是和代码同款会比较合理？

**Comment by lh1me** [comment]
不明白，现在的宽度不是就是页面宽度吗？

**Comment by YINNA63** [comment]
![image](https://user-images.githubusercontent.com/33350067/132136382-57dbfbb6-7fb6-4e93-b817-c28dc07992fb.png)

**Comment by YINNA63** [comment]
现在是根据代码长度变化的，代码只有五个字符时，代码块就只有五个字符长，超过页面的话代码块也会超出页面

**Comment by lh1me** [comment]
请查看 [Demo 站点](https://linhong.me)，现在并不是根据代码长度变化的。上面已经说过了，请 [关闭默认配置](https://github.com/lh1me/hexo-theme-aomori#using)。

**Comment by YINNA63** [comment]
OK, 抱歉之前操作有误
