### ISSUE TITLE
页面滚动到顶部，有时会出现进度条没有恢复到0的情况，侧边栏也没恢复定位

### ISSUE THREAD

**Issue by kiyass** [lh1me/hexo-theme-aomori#6]
页面整体非常的简洁美观，不过使用的时候偶尔会出现上述问题。

出现这个问题的主要原因是页面滚动到顶部时，函数执行间隔还没有到达30ms，所以函数没被执行。

可以改一下节流函数的代码，加一个延时执行。

**Comment by lh1me** [comment]
谢谢你提出的问题，后续我会抽空优化，同时也欢迎PR～
