### ISSUE TITLE
您好！非常喜欢这个主题，请问一下如何才能改变该主题的网页配色呀？

### ISSUE THREAD

**Issue by yuuyuu30** [lh1me/hexo-theme-aomori#66]
我尝试修改了themes\hexo-theme-aomori\source\stylesheets下的base文件里的颜色代码，hexo clean&hexo g&hexo d之后发现网页还是没有变化，只能来麻烦开发者解答了。
提前谢谢您！

**Comment by lh1me** [comment]
需要在主题目录下运行 **npm run build**

**Comment by yuuyuu30** [comment]
已解决，感谢您！
