### ISSUE TITLE
文章 cover配置的图片相对路径到底如何指定。

### ISSUE THREAD

**Issue by imoling** [lh1me/hexo-theme-aomori#79]
_post 目录中下文章的Front-matter cover配置，怎么指定到与文章md同名的文件夹目录下图片呢？同样，文章顶部图片如何相对路径显示出来呢？

**Comment by lh1me** [comment]
文章链接后拼上资源文件名就是了

假设文章链接 `https://a.com/xxx/`

那文章同名文件夹下图片链接就是 `https://a.com/xxx/a.png`

相对链接是指 `/xxx/a.png`

现在 `cover` 和 `photos` 是支持相对链接和完整链接
