### ISSUE TITLE
请问一下cover和photos不支持绝对链接吗

### ISSUE THREAD

**Issue by fnoopv** [lh1me/hexo-theme-aomori#8]
![image](https://user-images.githubusercontent.com/24599198/85949719-f1b4ba00-b98a-11ea-97d0-bb12626f7efe.png)
如图，下面文章正文的能解析出来，文章配置部分的两个无法加载出来

**Comment by wb014** [comment]
你好,我也遇到了这个问题,想请教一下解决方法,感谢

**Comment by lh1me** [comment]
文章配置项不支持绝对链接哦

**Comment by fnoopv** [comment]
> 你好,我也遇到了这个问题,想请教一下解决方法,感谢

换主题了，图片都在图床上，没办法
