### ISSUE TITLE
关于样式的小问题

### ISSUE THREAD

**Issue by unshell** [lh1me/hexo-theme-aomori#9]
### 1.sidebar过长时，post内容过少，不足以顶起footer。
![issue](https://user-images.githubusercontent.com/29560731/86578057-ca26a880-bfad-11ea-990d-36088b8b2f19.jpg)
### 2.设置 config.root 时，主题样式路径就不对了
正常情况下root:/完全OK,如果root:/blog/，样式路径就找不到

**Comment by lh1me** [comment]
主题路径问题已经修复了。

**Comment by unshell** [comment]
确实正常情况下是不会出现的，但是右侧工具栏Tags,Categories,Recent Posts,Achive 全开启的时候。
任意点一个Tags、Categories或者Achive，由于文章少，标签和分类多导致这种现象的情况还是有的。
而像博主给的展示模板来说Tags没有启用的情况几乎不会出现。
