### ISSUE TITLE
導航菜單未顯示

### ISSUE THREAD

**Issue by nataliepjlin** [lh1me/hexo-theme-aomori#95]
已閱[文檔](https://aomori.linhong.me/v/chinese/features/theme)，不確定教程的「全站」是指在theme裡面還是在外面Hexo預設的config.yml。如果是theme裡面的話，已設置如下:
![image](https://user-images.githubusercontent.com/100992247/160431395-4b1ee628-cb3f-4f13-b7a7-cf1f3d4d9446.png)
但在本地運行沒有顯示導航菜單
![image](https://user-images.githubusercontent.com/100992247/160431525-d9affc1a-f27f-4195-83c1-9eea58e7e1ba.png)

**Comment by lh1me** [comment]
全站指的是最外层 Hexo 根目录配置。

**Comment by nataliepjlin** [comment]
@lh1me 感謝!
